version: '2.2'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
      - node.name=elastic
      - cluster.name=es-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-eval01-data:/usr/share/elasticsearch/data
      - ./data:/usr/share/elasticsearch/config/data
    ports:
      - 9200:9200
      - 9300:9300

  frontend:
    build: ./webapp
    ports:
      - "80:80"


volumes:
  es-eval01-data:
    driver: local
